### ISSUE TITLE
Django 1.3 cannot import name patterns

### ISSUE THREAD

**Issue by davidportella** [laplacesdemon/django-social-friends-finder#1]
In django 1.3 is 
from django.conf.urls.defaults import pattern
but in url.py 
from django.conf.urls import patterns, url

**Comment by laplacesdemon** [comment]
I have fixed the issue with following
`from django.conf.urls import *`

I usually don't use star in imports since it's not comprehensive and pep8 is not happy with it. In this case, I had to.
