### ISSUE TITLE
How to use django-social-auth instead of django-allauth

### ISSUE THREAD

**Issue by jvorcak** [laplacesdemon/django-social-friends-finder#6]
Hi,

I've installed the your application to my Django env, but it somehow enforces me to use django-allauth, if I go to /find-friends/list I get

No module named allauth.socialaccount.models

So I guess it's trying to use allauth application

I'm using django-social-auth, is there a way I can use that to find all the friends?
I have the latest version of django-social-auth installed

Thanks

**Comment by laplacesdemon** [comment]
Hi, Are you sure that `SOCIAL_FRIENDS_USING_ALLAUTH` setting is False. I forgot to add this setting to the README file which I do it now.

**Comment by jvorcak** [comment]
With False I'm getting another error now

provider: %s is not implemented

self.social_friend_lists = SocialFriendList.objects.get_or_create_with_social_auths(self.social_auths)

**Comment by laplacesdemon** [comment]
Which social provider do you use? We support only facebook, twitter and vkontakte. If you use another provider than these, you have to develop the backend class for it. 

Besides, `NotImplementedError` is no longer raised. Are you using the latest version? If not you can remove the old one with `pip uninstall django-social-friends-finder` then install with `pip install git+https://github.com/laplacesdemon/django-social-friends-finder.git`.

Take a look at following files:

https://github.com/laplacesdemon/django-social-friends-finder/blob/master/social_friends_finder/models.py
https://github.com/laplacesdemon/django-social-friends-finder/blob/master/social_friends_finder/utils.py
